### ISSUE TITLE
To Do:  add support to add/view/delete user nicknames

### ISSUE THREAD

**Issue by mblackhamgw** [mblackhamgw/gwhelpdesk#1]

**Comment by hilocz** [comment]
And move / export - import . Currently nicknames can´t be moved, which is bad.

**Comment by mblackhamgw** [comment]
Limitation of a nickname.   you would have to delete old and create new, which might not be too difficult.
for export/import,  do you mean just nicknames or users also.   I hesitate to do import/export for a helpdesk application.

**Comment by hilocz** [comment]
I meant, when you moving user you can´t move the nickname ( for example user is admin, postmaster etc ) with him. Than it would be very helpful if the tool can move nicknames too.

**Comment by mblackhamgw** [comment]
If you move a user that has a nickname,  there is no reason to move the nickname with it.  The nickname references the user on the new post office.

There is an issue with moving a user that has a resource,  I'll try to see what I can do in this case.  I may just alert the admin that they would have to reassign the resource to another user using GW admin console.   Not sure I want to do that for this application.

**Comment by hilocz** [comment]
Morris I´m talking about nickname , which is created because you want, that the user will get emails for system name like admin@domain.com , postmaster@domain.com etc. There is much reason to move it with that user.
Or female user get married, there are plenty more use cases, when you need that nickname moved.

**Comment by mblackhamgw** [comment]
I don't agree with your scenario.   Here is proof.   A gw user: bbking on po of proov has a nickname called post master.  I sent an email to postmaster@idomain and it delivered to bbking on provo po.   I move the user to orem po and sent another email to postmaster@idomain and it  delivered tp bbking on orem po.

Details on the postmaster nickname before and after move:

before move:
Owning object:	BBKing.Provo.Utah

after move:
Owning object:	BBKing.Orem.Utah


screenshot of mailbox:
![image](https://user-images.githubusercontent.com/19786434/33226293-742e5858-d147-11e7-8f6b-1a29e45d22dd.png)

**Comment by hilocz** [comment]
Sorry, I totally forgot to tell you, that I´m currently doing migrations to new HW and the source post office will be deleted. I have post offices with hundreds of nicknames which need to be moved.
Sure, not every day task, but time to time we doing clean up of old data ( orphaned blobs ) with creating new post office a moving all users to it and deleting old post office.

**Comment by mblackhamgw** [comment]
David,   this is not a scenario I want to tackle with this application.  I't to much of a one-off situation.

**Comment by hilocz** [comment]
Ok, fair enough.  That I need to find out how to do it by myself ;).

**Comment by mblackhamgw** [comment]
Done with resources and nicknames for now,   May add some other stuff later
