### ISSUE TITLE
Possibility to add as helpdesk external email addresses

### ISSUE THREAD

**Issue by hilocz** [mblackhamgw/gwhelpdesk#4]
This is most wanted feature, which is not in GroupWise. Customers number one need is to have external email addresses in his system address book and be able to add it by itself.

**Comment by mblackhamgw** [comment]
David.   This is already possible with both GroupWise and this app.

They need to create a new Non-Groupwise domain,  then create a Postoffice in that domain.

Then you can add users to that post office.     Be sure to override the users Internet Domain name and assign it as "known elusively by..."  Then check the user format override and enter the user portion of the email addr as the Preferred Email ID.

With my app,  you would need to go thru those steps as well.  When you create a user,  the external  postoffice should be selectable.

--Morris

**Comment by mblackhamgw** [comment]
BTW:  I could easily create a python script outside of my app to import a list of external users and addrs from a csv file.   the csv would probably need to have first name, last name and the email address.  I can get the userId and idomain from the address.  Let me know if this would be helpful.

MB

**Comment by hilocz** [comment]
Morris, the python script would be very helpful as the is every time a list and sometimes is very long.
Thanks.

**Comment by mblackhamgw** [comment]
Do you have a sample csv file?

**Comment by mblackhamgw** [comment]
David,  here are Linux and Windows executables in the attached zip file.  Instructions are in the readme.
Not sure what Linux OS's it will run on,  I compiled it with openSuse 42.2,   GLI BC version is sometimes and issue.
[imporexternals.zip](https://github.com/mblackhamgw/gwhelpdesk/files/1400329/imporexternals.zip)


Good Luck with it..

**Comment by hilocz** [comment]
Morris, I will test it and report back, thanks a lot.

**Comment by hilocz** [comment]
Hi Morris, how difficult will be change the utility to import nicknames from export done in gwadmin console .
CSV header 
"name","postoffice","domain","username","expirationdate","visibility"
